### ISSUE TITLE
[FEATURE] Add support for TYPO3 12

### ISSUE THREAD

**Issue by eliashaeussler** [eliashaeussler/typo3-warming#174]
### Is your feature request related to a problem?

TYPO3 12 is released, so EXT:warming should soon be compatible with the new major version.

### Describe the solution you'd like

Add support for TYPO3 v12.4 LTS. If needed, drop support for TYPO3 10.4 and increase minimum requirement for PHP to 8.0.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### ToDo

- [x] Upgrade to TYPO3 12.4
- [x] Drop support for TYPO3 < 12.4
- [x] Upgrade to PHP 8.1
- [x] Add support for `eliashaeussler/cache-warmup` 2.x
- [x] Drop support for `eliashaeussler/cache-warmup` < 2.0
- [x] Use `cuyz/valinor` instead of `symfony/serializer`
- ~Rewrite cache handling (see EXT:solver → https://github.com/eliashaeussler/typo3-solver/tree/main/Classes/Cache)~
- [x] Add acceptance tests, #320
- [x] Modernize PHP + JS codebase
- [x] Add events, #338
- [x] Add TypoScript config for templates, #333
- [x] Read all sitemaps from `robots.txt`, #336
